project:
  type: website

website:
  title: "Sarah E. Sdao"
  navbar:
    left:
      - href: index.qmd
        text: <i class="bi bi-house"></i> HOME
      - href: about.qmd
        text: <i class="bi bi-card-list"></i> RESUME
      - href: writing-samples.qmd
        text: <i class="bi bi-pencil"></i> WRITING SAMPLES
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/sarahsdao/"
        aria-label: "LinkedIn Profile"
      - icon: github
        href: "https://github.com/sarahsdao"

format:
  html:
    toc: true
    brand: _brand.yml
