project:
  type: website
  output-dir: docs/

website:
  title: "Sarah E. Sdao"
  navbar:
    left:
      - href: index.qmd
        text: <i class="bi bi-house"></i> HOME
      - href: about.qmd
        text: <i class="bi bi-card-list"></i> RESUME
      - href: writing_samples.qmd
        text: <i class="bi bi-pencil"></i> WRITING SAMPLES
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/sarahsdao/"
        aria-label: "LinkedIn Profile"
  site-url: https://sarahsdao.github.io/sarah-sdao/

format:
  html:
    toc: true
    brand: _brand.yml
